### ISSUE TITLE
Zone.cancelTask error in Angular 2.0.0-beta.11 

### ISSUE THREAD

**Issue by cquillen2003** [valor-software/ng2-dragula#165]
After upgrading to Beta 11, the following error occurs after dropping an item into a bag:

EXCEPTION: Error: Task does not support cancellation, or is already canceled.

STACKTRACE:
at ZoneDelegate.cancelTask (eval at <anonymous> (http://localhost:8080/js/vendor.js:401:2), <anonymous>:369:24
at Zone.cancelTask (eval at <anonymous> (http://localhost:8080/js/vendor.js:401:2), <anonymous>:279:45)
............

**Comment by NathanWalker** [comment]
This was an issue with `zone.js` which is now fixed today with `0.6.5`... update your zone to that version and it will be fixed.

I'll update the deps on this project soon.

**Comment by NathanWalker** [comment]
@cquillen2003 Actually looks like it may need another angular beta update as the issue comes from angular2-polyfills which is part of the angular distro... They will probably release another beta soon which will use the latest `0.6.5` zone.js which contains the fix and will fix angular2-polyfills at that time.
