### ISSUE TITLE
undef is not defined error while using ng2-dragula in my sample project

### ISSUE THREAD

**Issue by harishrohokale** [valor-software/ng2-dragula#229]
Hi Guys,
I have gone through your readme. 
1. did npm install ng2-dragula dragula --save
2. added directives and viewProviders
    here is the code snippet import {Dragula, DragulaService} from 'ng2-dragula/ng2-dragula';
3. then added ng2-dragula in HTML

Please find attached screenshot.

![ng2-dragula issue](https://cloud.githubusercontent.com/assets/6389000/14877053/9c1edb56-0d37-11e6-81a7-abd5330c08e4.png)

**Comment by valorkin** [comment]
it seems you have an issue in ticky.js

**Comment by lorenjerickson** [comment]
Not sure I agree with this assessment.  Had the same problem myself and after much research found that somehow I had ng2-dragular 1.1.9 running against 3.6.x dragula.  Probably because I was following the ng2-rc.1 update *very* closely. Re-installed ng2-dragula@1.1.9 and pinned dragula to 3.7.0, now everything is happy.  Hopefully, @harishrohokale  is still listening.  Regardless, this was never a "ticky problem".

**Comment by valorkin** [comment]
I just assumed from error stack, thanks for solving!

**Comment by lorenjerickson** [comment]
my apologies, this was a problem with ticky after all.  v.1.0.1 of ticky fixes this issue.  raises an interesting question about who is responsible for verifying downstream dependencies, though.  maybe this should have been caught by the dragula or contra folks.  anyway, thanks for a great adaptation of this library for ng2.

**Comment by valorkin** [comment]
@nzgb should knew more about it :)
