### ISSUE TITLE
Angular2 RC compatibility

### ISSUE THREAD

**Issue by hmlb** [valor-software/ng2-dragula#243]
Hello Valor software team!

With the release of angular 2.0.0-rc.0, some changes needs to happen for ng2-dragula integration in angular apps.  

It should be limited to dependency update and import namespace modifications like  'angular2/core' -> '@angular/core'  

I've started to work on it but I'll have very little time to finish this so I prefer to open this issue :) 

Thanks for your nice work !

**Comment by lorenjerickson** [comment]
+1

**Comment by likerRr** [comment]
Also very need it

**Comment by jan-zajic** [comment]
+1

**Comment by jan-zajic** [comment]
btw PR #239 exists from xtiancapil, can someone look why it fails?

**Comment by thomasbee** [comment]
+1. please this is very straightforward

**Comment by xtiancapil** [comment]
@jan-zajic the build was failing due to an incorrect configuration of .travis.yml file due to:

1. Having an `npm test` step which tried to run karma tests that the project didn't have.
2. When it tries to run `npm install` it tries to install phantomjs and fails. This is a known [travis-ci issue](https://github.com/travis-ci/travis-ci/issues/3225).

It should be passing now. I removed the test step and added a before_install script to install phantomjs manually.

**Comment by hirtie-maxim** [comment]
+1

**Comment by menonsamir** [comment]
+1

**Comment by denodaeus** [comment]
+1

**Comment by hmlb** [comment]
The PR #239 was merged but until the issue #249 is not solved, ng2-dragula remains unusable with angular RC

**Comment by valorkin** [comment]
Published to npm, please check
im some write to #249

**Comment by hmlb** [comment]
Ok I will, thank you @valorkin

**Comment by valorkin** [comment]
check 1.1.9 it seems working fine now

**Comment by likerRr** [comment]
@valorkin thx for update. But wouldn't it be better to update *patch* version instead of *minor* cuz it brings backwards incompatible changes for those who adds dependencies to `package.json` like `"ng2-dragula": "^1.1.6"`

**Comment by valorkin** [comment]
It will be so, as soon as ng2 will be released
