### ISSUE TITLE
Multiple Drag and Drop

### ISSUE THREAD

**Issue by poonsv** [valor-software/ng2-dragula#283]
I have a requirement to select multiple items and drag & drop to another container all at once.
Will this feature be on the roadmap?

**Comment by stefanmeschke** [comment]
Did you found a solution for this?

**Comment by poonsv** [comment]
No, it seems that nobody offer such solution under Angular 2.

**Comment by maxfahl** [comment]
I'm looking for this as well since my current project is depending on it. I guess I will have to come up with a custom solution. My plan is to create a Selector module and a DragAndDrop module and have them work together. If I create those as stand-alone modules I will report back here.

**Comment by centogram** [comment]
@maxfahl were you able to find a solution to handle multiple select?

**Comment by Mohendran** [comment]
Did anyone find a solution to this?

**Comment by cormacrelf** [comment]
This is a bit out of scope for ng2-dragula. You would have to:

* Maintain a list of selected items yourself, via checkboxes
* Handle drops manually, without relying on the dragula model's inbuilt array manipulation
* If you know there is a multiple select going on, move all the items instead of just one
* The hardest part is displaying a different drag preview when multi-select is in play using plain CSS and usually-invisible divs.
* It might be possible to do a red-dot-with-number thing, as long as the HTML was rendered into the template before you picked it up.

Overall, it can be done, but it will be very tied to your own data models. Neither ng2-dragula nor dragula itself is in a position to do that for you. It will be a little awkward, given the limits of drag previews in dragula. For more control you might like to build a fully custom solution including an in-flight renderer using my https://github.com/cormacrelf/angular-skyhook

**Comment by maxfahl** [comment]
@centogram we came up with another solution to our problem for now. Ill come back to you if we decide to implement this feature later on. It's a little weird that no library seems to deal with this use case, it can't be that uncommon.

**Comment by sergiomcunha** [comment]
@maxfahl do you've gone into multi selection solution?

**Comment by kreuzerk** [comment]
I recently came across this issue because I did not find a library with support for multi drag and drop. I decided to go on and implement ng-sortrgid which is now available on npm. 🚀

https://www.npmjs.com/package/ng-sortgrid

I thought I share it here as this might be helpful to some of you.  Feel free to try it out.
