### ISSUE TITLE
Angular 2 + dragula {error:Can't bind to 'dragula' since it isn't a known property of 'ul'}

### ISSUE THREAD

**Issue by Apps-23** [valor-software/ng2-dragula#418]
I had an error it showed : "ng2-dragula has no exported member 'Dragula'"

So instead of using Dragula , I used DragulaModule

So my .ts file has:

import {DragulaModule , DragulaService} from "../../../node_modules/ng2-dragula/ng2-dragula"

and inside component: directives: [DragulaModule], viewProviders: [DragulaService]

but while using the code in html template of the component:

```
<ul style="list-style: none" *ngIf="data1.status_code!=404" [dragula]='"bag-one"' [dragulaModel]='data1' class="collection">

<li *ngFor="let project of data1"  >

<div class="col-md-4">
<div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">
            <favourite></favourite>  
            {{project.project_id}}:{{project?.project_name}}
          </h4>
        </div>     
</div>    
</div>   

</li>
</ul>
```

I get the error: Can't bind to 'dragulaModel' since it isn't a known property of 'ul'

**Comment by paesku** [comment]
@Apps-23 the **directives** isn't a valid component property anymore. Instead you should load Dragula with the **NgModule** Decorator. 

```typescript
import {DragulaModule , DragulaService} from "../../../node_modules/ng2-dragula/ng2-dragula"

@NgModule({
  imports: [
     DragulaModule
  ],
declarations: []
})
```

Then it should work.

**Comment by mayconjcm** [comment]
Ok. But, after that, how to use DragulaService properly?

When i try to Import the DragulaService i always get the error: 

Error: Module ./node_modules/ng2-dragula/ng2-dragula.js does not export DragulaService (imported by ./component.js)

Perhaps because the lib (Ng2-Dragula) isn't exporting DragulaService, only DragulaModule.

Any suggestions?

**Comment by paesku** [comment]
did you properly import the **DragulaService** within the component from **ng2-dragula/components/dragula.provider** ?

Example:  

```typescript
import {
  Component,
} from '@angular/core';
import { DragulaService } from 'ng2-dragula/components/dragula.provider';
@Component({
  selector: 'some-selector',
  template: `template goes here`,
})
export class ListEditorComponent {

  constructor(private dragulaService: DragulaService) {
    dragulaService.drop.subscribe(value => this.onDrop());
    dragulaService.setOptions('bagName', {
      invalid: () => false
    })
  }

 onDrop() {
    // do something
  }
}

```

**Comment by mayconjcm** [comment]
Now its working, thanks @paesku !

Can we insert this in Docs or export DragulaService globally?

Thanks again!

**Comment by paesku** [comment]
Just read the source files and basically **import { DragulaService } from 'ng2-dragula/ng2-dragula';** should work as well.

**Comment by mayconjcm** [comment]
[Works] ::: import { DragulaModule } from 'ng2-dragula/ng2-dragula';
[Works] ::: import { DragulaService } from 'ng2-dragula/components/dragula.provider';

[Does not] ::: import { DragulaService } from 'ng2-dragula/ng2-dragula';

Btw, your solution works as well!

**Comment by dongtong** [comment]
@paesku @mayconjcm 

I also have "main.bundle.js:8977 Unhandled Promise rejection: Template parse errors:
Can't bind to 'dragula' since it isn't a known property of 'div'"

1. Import DragulaModule

```
import { NgModule }                      from '@angular/core';
import { CommonModule }                  from '@angular/common';
import { FormsModule }                   from '@angular/forms';
import { DragulaModule }         from 'ng2-dragula/ng2-dragula';

@NgModule({
    imports: [
        CommonModule,
        FormsModule,
        DragulaModule
    ],
    declarations: [
        //....
    ],
    providers: [
       //....
    ]
})
```

2. Import service

```
import { DragulaService } from 'ng2-dragula/components/dragula.provider'

//....
constructor(
        private dragulaService: DragulaService
    ) {
        dragulaService.setOptions('eligible-rate', {
          copy: true
        });
        
        dragulaService.drag.subscribe((value) => {
          console.log(`drag: ${value[0]}`);
          this.onDrag(value.slice(1));
        });

        dragulaService.drop.subscribe((value) => {
          console.log(`drop: ${value[0]}`);
          this.onDrop(value.slice(1));
        });
    }

```

3. Use it

`<div *ngFor="let item of items" [dragula]='"test"' [dragulaModel]='items'></div>`

But Still report :"Can't bind to 'dragula' since it isn't a known property of 'div'"

**Comment by paesku** [comment]
@mayconjcm your code looks totally fine. Your service is working fine? And you are importing DraguleModule on a top level module?

**Comment by mayconjcm** [comment]
You mean @dongtong ? Btw, my code is working fine...

**Comment by GrushinEgor** [comment]
@dongtong It's happens because of your component has his own parent module (Maybe you've added some routing module or your component is a part of separated module). 

I've faced with this issue too and solved it when realized that my component was a part of separated module. I've just move import to its parent and there we go!
