### ISSUE TITLE
how do you cancel the drop event?

### ISSUE THREAD

**Issue by nmorado** [valor-software/ng2-dragula#438]
thanks

**Comment by sengfan** [comment]
I have the same question. need help. Thanks

**Comment by nmorado** [comment]
this seems to work for me

dragulaService.find('mybag').drake.cancel(true)

**Comment by sengfan** [comment]
Thank you so much.

**Comment by dongtong** [comment]
@nmorado 
when to execute above code? onDrag ? onDrop? or other?

**Comment by nmorado** [comment]
On drop for me

**Comment by daintym0sh** [comment]
@nmorado 
For some reason this is not working for me. The cancel method is executing but has no effect. I inserted a breakpoint within onDropModel and can confirm that it is being executed. 

Class:
```
public players: Player[];

public selectedPlayers: Player[];

constructor(private dragulaService: DragulaService, private playerService: PlayerService) {

  this.selectedPlayers = new Array<Player>();

  this.players = playerService.getPlayers();

  this.dragulaService.dropModel.subscribe((value) => {
    this.onDropModel(value.slice(1));
  });
  
}

private onDropModel(args) {
  let [el, target, source] = args;
  this.dragulaService.find('first-bag').drake.cancel(true);
}
```

Template: 
```
<div class='wrapper'>
  <div class='container' [dragula]='"first-bag"' [dragulaModel]='players' fxLayout="row" >
    <div  *ngFor='let player of players'>
      <div>{{player.$LastName}}</div>
    </div>
  </div>
  <div class='container' [dragula]='"first-bag"' [dragulaModel]='selectedPlayers' title="selection" fxLayout="row" >
    <div *ngFor='let player of selectedPlayers'>
      <div>{{player.$LastName}}</div>
    </div>
  </div>
</div>
```

**Comment by D3K0** [comment]
@daintym0sh same problem here, did you find any solution?

**Comment by daintym0sh** [comment]
@D3K0  I never figured it out and ended up using another part of the Dragula library to accomplish my task. 

I wanted to limit containers within a 'bag' to hold only one item at a time. I wrote logic inside of he 'accepts'  function within setOptions to do this: 
```
    this.dragulaService.setOptions('first-bag', {
      accepts: (el, target, source, sibling) => {
        if (target.title === 'selection' && this.selectedPlayers.length > 0){
          return false;
        }else{
          return true;
        }
      }
    })
```
If the list of selectedPlayers has length > 0, then containers with title 'selection' will not accept new elements.

Regarding the 'cancel' method, I wonder if it doesn't have the desired effect due to the fact that I'm using Flex-Layout on my container elements. I spent a while trying to figure it out with no luck.

**Comment by ersurajnegi** [comment]
i tried the solution as below in onDrop event : 
this.dragulaService.find('first-bag').drake.cancel(true);

it is getting executed but getting console error as below: 

**core.es5.js:1020 ERROR DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.**

any Idea how to resolve this?

**Comment by fahadhussain2** [comment]
@ersurajnegi I am also getting the same error while cancelling the drop event? How to solve it ?

**Comment by mindless-coder** [comment]
In an Angular project, drake.cancel(true) was not working from dropModel, except that if I stepped through I could see the elements being properly removed from the DOM and being added back afterwards.  I found that the model is still getting updated even after the cancel, and that made it look like the drop had not been cancelled.  Here is what I did to revert the model as well:
`this.dragulaService.find(this.dragGroup).drake.cancel(true);
 sourceModel.splice(sourceIndex,0,...targetModel.splice(targetIndex,1));`

**Comment by federica1992iola** [comment]
Hello, I have the same problem because my groups structure is recursively. I've resolved put this code on **dropModel** subscription 

![image](https://github.com/valor-software/ng2-dragula/assets/20588320/81f6c086-35ef-41d4-b4ce-202db05fadad)

My structure of mock data for render nested items is this

![image](https://github.com/valor-software/ng2-dragula/assets/20588320/2a164cf4-9507-4979-a9ff-d8f0719707dd)

My view code is

![image](https://github.com/valor-software/ng2-dragula/assets/20588320/0c1d7b2a-ba45-4387-ac26-3b6414808eb3)

Hope these can be helpfull for someone :)
