### ISSUE TITLE
Bag named: "section-bag" already exists

### ISSUE THREAD

**Issue by Bhushan001** [valor-software/ng2-dragula#442]
hi ,
I have a sectionComponent which has another component.

section.component.html

`<div [dragula]='"section-bag"'>
  <*ngFor="let row of section.rows">
   <row [row]="row">Loading....</row>
</div>`

section.component.ts

`constructor(private dragulaService: DragulaService) {
    this.dragulaService.setOptions('section-bag', {
      revertOnSpill: true
    });
  }`

now when I am adding a new section, it says 

> Bag named: "section-bag" already exists

any solution?

**Comment by KamilaKurys** [comment]
@Bhushan001 have a look on `setOptions` method https://github.com/valor-software/ng2-dragula/blob/1f872dd8d33e386ca89cceb40d37f37582a39f7d/components/dragula.provider.ts#L66 it can give you an idea why this is failing.
You can try do something like below
```
constructor(private dragulaService: DragulaService) { 
  const bag: any = this.dragulaService.find('section-bag');
  if (bag !== undefined ) this.dragulaService.destroy('section-bag');
  this.dragulaService.setOptions('section-bag', { revertOnSpill: true }); 
}
```

**Comment by Bhushan001** [comment]
@KamilaKurys  thanks  for the update :)

**Comment by borislemke** [comment]
I think a better solution would be to implement a unique ID for each bag:

```javascript
some.component.ts
...

let _uniqueId = 0;

@Component({
    ...
    template: `
         <div [dragula]="uniqueBagId"></div>
    `
})
export class AComponentThatUsesDragula {

    uniqueBagId: string;

    constructor(private dragulaService: DragulaService) {
         this.uniqueBagId = 'dragula-bag-' + _uniqueId++;

         dragulaService.setOptions('section-bag', { revertOnSpill: true } );
    }
    ...
}

```

**Comment by atul-wizni** [comment]
It will be better to provide unique DragulaService to each SectionComponent instead of sharing common service:

`@Component({
    ... , 
    providers: [DragulaService],
    ...
})
export class SectionComponent {
    ...
}`

**Comment by Gillardo** [comment]
I agree with a separate service for each

**Comment by borislemke** [comment]
@Gillardo it will not solve the issue when multiple instances of the same component are created. See my updated comment above on how to circumvent this.

**Comment by balazsnemeth** [comment]
I think the most clean solution is to keep the given bag only until it is needed, so I sorted out this issue by calling `setOptions` in `ngOnInit()` and destroy it in `ngOnDestroy()`:

```
 ngOnInit() {
      ...
      this.dragulaService.setOptions(this.draggerContainerName, {
            moves: function (el, container, handle) {
                return handle.className.indexOf('ads-dragger') >= 0;
            }
        });
        ....
 }
```

and 
```
 ngOnDestroy() {
        this.dragulaService.destroy(this.draggerContainerName);
    }
```

**Comment by MartinJHammer** [comment]
@balazsnemeth Super simple solution. Added

```
ngOnDestroy() {
        this.dragulaService.destroy("column-bag");
    }
```

to my  component and the problem was solved. Thanks!

**Comment by ankeknicker** [comment]
@MartinJHammer for me, this doesn't do the trick completely, if I just use
`public ngOnDestroy() {
      this.dragulaService.destroy('myBag');
}`

I had to add an additional condition: 
`public ngOnDestroy() {
      if (this.dragulaService.find('myBag') !== undefined) {
            this.dragulaService.destroy('myBag');
      }
}`

This condition was needed in my case, because I discovered, that in some cases, there were no bag present in dragulaService and the destroy command caused an 'Error during cleanup'

**Comment by jiggy1com** [comment]
I like @KamilaKurys solution. 
The unique ID solution from @borislemke is OK, but then you're just stuffing objects you no longer need.

I have a deep nested loop in the template & TS using a unique ID for each element in the array. It's important those stay in sync so I'm not dropping ish all over the place. Plus my items are in a <tabset> so toggling tabs created an issue. 

@KamilaKurys thanks for the solution, or short cut to finding it =) I figured there had to be a way to remove an existing bag. Probably in the docs smh

**Comment by pranavgawri** [comment]
I am facing same problem. I have a component "category component" of which multiple instances have to be created. Now if I use the solution suggested by @borislemke then for each instance I will have to provide a unique id, which I think is a workable solution, but how do I maintain that "id"?? 
I mean when a category component is destroyed (here I will destroy the bag also, as suggested by @balazsnemeth ) and then recreated then I should be using the same "id" that was being used earlier right?? Otherwise everytime the category.component is destroyed/recreated (for example due to a *ngIf condition) I will keep attaching new bags.

I hope I have explained my point correctly, kindly let me know if its unclear. 

Please provide your valuable inputs.

Thanks.

**Comment by hmuller** [comment]
@KamilaKurys Does it mean setOptions could be used only once per bag?

**Comment by souflam** [comment]
@KamilaKurys thnks for your help :)

**Comment by cormacrelf** [comment]
Note from maintainer:

DO NOT use multiple instances of DragulaService. Do not inject it into each component instance. You must destroy a group (formerly ‘bag’) if you want to call createGroup again. You can use name spacing of the group name to avoid collisions, but you will want to destroy groups anyway.
