### ISSUE TITLE
How to allow drag and drop only for respective panel and restrict for other panel

### ISSUE THREAD

**Issue by chandru02010** [valor-software/ng2-dragula#474]
I am loading multiple panels using ng-repeat, In each panel there are list of child items which I wanted to arrage. For each panel I added this  **dragula='"first-bag"'**.
Right now I can move an item from one panel to another panel but this I dont want.
I want to allow drag and drop only for respective panel and restrict for other panel.

And more thing, is it possible to arrange each panel using this drag and drop (vertically). So that I can arrange **parent panels** and also its **child items within respective panels**.

**Comment by mtrdp642** [comment]
To prevent moving from one panel to another, each panel will need a different bag name, so panel 1 will have bag name of 'panel1', panel 2 will have bag name of 'panel2', etc. Since you're using ng-repeat, using a function to generate a random string and using that value as the bag name would work. Another option is to subscribe to an event and check if the target and source bags are equal; if they are equal, then allow the event, if they are not equal, cancel the event.

In order to have parent panels movable as well as child items movable, you'll need nested dragula elements within the HTML and the Angular2 components. The outermost bag of items will have a bag name such as 'panelBag', while each of the nested dragula bags will have a unique name, differentiating each bag item from one another (see first paragraph). The outermost bag will allow for the parent panels to be moved around and the nested bags will allow for the child items to be moved, while the unique child bag names will prevent the child items from being moved from one panel to another.

**Comment by jesus-novologic** [comment]
I have the same issue, anyone can help with this please?

**Comment by kersten** [comment]
@chandru02010, @jesus-novologic  Your first point should work with setting ```dagula="{index}-bag"``` where index should be a dynamic value.
