### ISSUE TITLE
Long touch/Hold doesn't drag

### ISSUE THREAD

**Issue by wasa4587** [valor-software/ng2-dragula#517]
I'm trying using a chrome on android phone, 
When i do a long touch (or hold) it doesn't drag the element nor fires any event. endeed i only can scroll the screen.
is there some way to config this?

**Comment by valorkin** [comment]
didn't found yet, but I need it too
if you will knew how, please drop me a note

**Comment by ivanov-v** [comment]
same problem

**Comment by cormacrelf** [comment]
Dunno what the problem is, but I have a demo repo I haven't tried on Android yet. I think mobile browsers generally want to see touchmove handlers on stuff; iPhones try to scroll and drag at the same time without a touchmove handler, for example. Try it out and tell me how it goes? To verify my theory on android you'd have to delete the autoscroll code, then `$ ng serve --host <your-computer's-ip-address>`, and try dragging the yellow and green children.

https://github.com/cormacrelf/dragula-touch-demo

**Comment by januslo** [comment]
@cormacrelf follow your demo and try to implement one, works in iOS but not android with crosswalk or chrome in web.

**Comment by munkhbayar17** [comment]
Yes, exactly same issue. Drag is not working on Nexus 5 touch screen because background is also scrolling (causing shake).

**Comment by cormacrelf** [comment]
This is a problem in literally every touch enabled browser, with every single drag and drop lib. I don’t think we have to solve it here in particular.

**Comment by yosigolan** [comment]
hey @cormacrelf 
i dont understand your answer. on android devices its almost not usable since users cant understand why the item is not dragged. there is no solution for that?

**Comment by cormacrelf** [comment]
I mean it very very literally. This is also a problem on iPhone, Chrome/Win10 Touch, iPad, and anywhere else the “back” gesture works. At least that’s my understanding of the android problem described here. I don’t have such a device, so I cannot say for sure. If it is the same, I’m not in a position to fix it because there is no “back gesture” event to listen to, and if it is android-specific... I’m still not in a position to fix it.

**Comment by yosigolan** [comment]
Hey @cormacrelf 
Thank you for your quick response. 
actually, you dont need an android device to reproduce it, it happens also in the browser in mobile mode. you can reproduce it on dragula demo (https://valor-software.com/ng2-dragula/index.html). just enter mobile emulator using chrome developer tools, select galaxy phone for example and click on an item and hold. you will see its not dragable this way. if you click on an item and immediately move the mouse its does work.

Yosi

**Comment by EmadFani** [comment]
anyone has a fix for this ?
