### ISSUE TITLE
Hook to confirm / cancel a drop ?

### ISSUE THREAD

**Issue by mildful** [valor-software/ng2-dragula#552]
Hi,

I was wondering if there is a built-in feature that allows executing some code to confirm / cancel a drop.
For example : a popup, an http request before dropping etc.

Thanks a lot.

**Comment by amanmathur99** [comment]
I was wondering the same thing. If there is nothing built in, can anyone recommend a way to do this?

**Comment by TenzinLama** [comment]
I'm also wondering how to do this

**Comment by cp79shark** [comment]
There doesn't appear to be a built-in way of doing this, but you can do it like this (and build it out/improve as you need). 

```
        this.dragulaService.drop
            .switchMap((v, i) => {
                return Observable.of({
                    confirmed: window.confirm('Confirm'), // your confirm action
                    event: v // the original drop event
                });
            })
            .subscribe((v: any) => {
                const confirmed = v.confirmed;
                const event = v.event;

                if (confirmed === false) {
                    this.dragulaService.find('BAG_NAME').drake.cancel(true);
                }

                // any additional drop processing
        });
```

**Comment by pierfreeman** [comment]
The solution proposed by @cp79shark seems to be a good idea (i would just put an else for the confirmed drop event.

The problem I encountered, is that when I don't confirm, the flow enters correctly in the if branch and the drake.cancel seems to be triggered, but the <div> I'm moving doesn't return in the source container in the DOM, unless if I update the page (which is the evidence that the drake.cancel works, otherwise the element would be in the target container after the page update too).

How can I fix this? Anyone which stepped into this problem too?

**Comment by soniyapampoori** [comment]
can you share your full source code. When dealing with this code I am getting " this.dragula.drop.switchMap is not a function" error

**Comment by cp79shark** [comment]
@soniyapampoori Full source isn't going to help. But here is the constructor from my component (which is where you're problem probably starts).  For context, this particular component handles reordering child elements.

You must have Angular inject the `DragulaService` shared-service. This is where `.drop` lives and it's an `EventEmitter<any>` which derives from rxjs' `Subject`. `switchMap` and `flatMap` are declared as extension methods in rxjs against `Observable` which `Subject` derives from.

All that to say that without seeing your code,  my best-guess is that you're not injecting the DragulaService, as there isn't really any reason for it to not exist. Also make sure you mark your `DragulaService` as `private`, `protected`, or `public`; otherwise it won't be available outside the `constructor()`.

If you're not familiar with how RxJS works, Google will find plenty of resources for you.

```
    constructor(private classService: ClassificationService,
        private modalService: NgbModal,
        private viewRef: ViewContainerRef,
        private dragService: DragulaService,  /// <--- You need this
        private toastService: ToastService,
        private appConfig: AppConfig,
        private elRef: ElementRef,
        private changeRef: ChangeDetectorRef
    ) {
       // ... other code

        this.dragService.drop
            .switchMap((v, i) => {
                return Observable.of({
                    allowed: this.dragEnabled,
                    event: v
                });
            })
            .flatMap(v => {
                const allowed = v.allowed;
                const event = v.event;

                if (allowed === false) {
                    this.dragService.find('classBag').drake.cancel(true);
                    return;
                }

                // this event won't be fired by Dragula if it's the same element/index
                const indexCurrent = event[1].tabIndex + 0;
                // since Dragula uses "after" sibling for v[4], if we're moving down, we need to subtract one
                // from the index to get the correct index
                const indexNew = ((event[4]) ?
                    ((event[4].tabIndex > indexCurrent) ? event[4].tabIndex - 1 : event[4].tabIndex) :
                    (this.classifications.length - 1) + 0); // if v[4] is empty then we're at the end of the list

                // update all the elements
                const elements: any[] = event[2].querySelectorAll('[tabindex]');
                Array.from(elements).forEach((el: any, index: number, arr: any[]) => {
                    el.tabIndex = index;
                    const id = el.dataset.id;
                    const pc = this.classifications.find(va => va.id === id);
                    if (!pc) { return; }

                    pc.priority = index;
                }, this);

                const currentReorderSet: { [id: string]: number } = {};

                // update list
                Array.from(elements).forEach((va: any) => currentReorderSet[va.dataset.id] = va.tabIndex, this);

                this.listContainer = v[2];

                this.actionInProgress = true;

                return this.classService.reorderBulkPreferredClassification(currentReorderSet);
            })
            .subscribe((v) => {
                if (v === true) {
                    this.toastService.success({
                        title: 'Success',
                        msg: `Order updated.`
                    });
                    this.actionInProgress = false;
                } else if (v === false) {
                    this.revertOrder();
                    this.toastService.error({
                        title: 'Oops',
                        msg: `Order could not be saved.`,
                        timeout: 5000
                    });
                    this.actionInProgress = false;
                }
            },
            (error) => {
                this.revertOrder();
                console.error(error);
                this.toastService.error({
                    title: 'Oops',
                    msg: `Order could not be saved due to a server error.`,
                    timeout: 5000
                });
                this.actionInProgress = false;
            });
}
```

**Comment by mumumilk** [comment]
hello @cp79shark  thanks for your answer, it worked.

But do anyone knows how to prevent dropping based on a request to backend (an asynchronus event).
Eg:

`this.dragulaService.drop
      .flatMap((v, i) => {
        return this.MyService.SomeObservableThatAwaitsBackendResponse();
      })
      .subscribe((v: any) => {debugger
        this.dragulaService.find('my_bag').drake.cancel(true);
      });
`
I've tried many things but i can't prevent from dropping when response arrives, and i can't understand why it works with waiting a window.confirm, but won't with waiting a response...
Any help would be great!

**Comment by cormacrelf** [comment]
window.confirm is one of the only synchronous wait APIs in all of Browser JavaScript. It literally pauses the entire VM until someone clicks Ok or Cancel. When it comes back, you can still cancel the current drag because you’re still in the event handler.

With async RxJS, when a call comes back it’s in the next VM tick. The event handler has completed without cancelling. You cannot cancel it any more. You can *probably* point to a line of code in Dragula like the following:

```js
handleEvent(e);
if (currentDrake.cancelled) {
   // ...
}
```

When you queue a task with setTimeout or HTTP, handleEvent will complete **immediately**, go to the next line, and the cancelled property will be false.

I would probably just allow the drop and show a spinner until the call comes back. If the call fails, reverse it by storing what happened or keeping a copy of the array handy with `Array.slice()`. I think this is essentially what @cp79shark is doing in a convoluted way.

As this is essentially all you can do, and is neither a bug nor something we are going to add to the library, I think that’s about it.
