### ISSUE TITLE
dragulaModel throws exception

### ISSUE THREAD

**Issue by twleo** [valor-software/ng2-dragula#653]
I am using dragulaModel on two tables in the same "bag".  When I drag one row from one table to the other, I get an exception Uncaught TypeError: Cannot read property 'splice' of undefined and row cannot be dropped.  Both tasks and agentATasks are defined and populated in the component.ts.  Need help to solve this problem.  Thanks

Below is my html
```
   <table class="table">
        <thead class="text-primary">
            <tr>
                <th>Task ID</th>
                <th>Ref #</th>
                <th>Customer Name</th>
                <th>Doc Type</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody [dragula]='"team-bag"' [dragulaModel]="tasks">
            <tr *ngFor="let t of tasks">
                <td>{{t.id}}</td>
                <td>{{t.refNbr}}</td>
                <td>{{t.custName}}</td>
                <td>{{t.docType}}</td>
                <td>{{t.receiveDate}}</td>
            </tr>
        </tbody>
    </table>
    
        <table class="table">
        <thead class="text-primary">
            <tr>
                <th>Task ID</th>
                <th>Ref #</th>
                <th>Customer Name</th>
                <th>Doc Type</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody [dragula]='"team-bag"' [dragulaModel]="agentATasks">
            <tr *ngFor="let t of agentATasks">
                <td>{{t.id}}</td>
                <td>{{t.refNbr}}</td>
                <td>{{t.custName}}</td>
                <td>{{t.docType}}</td>
                <td>{{t.receiveDate}}</td>
            </tr>
        </tbody>
    </table>
```

**Comment by adunn49** [comment]
I've only just started using ng2-dragula in my project and have spent the past day battling with a similar "Cannot read property 'splice' of undefined" error in the console. Using Chrome Developer Tools to debug ng2-dragula, I could see that the model being passed into the 'dragulaModel' attribute was undefined at the point ng2-dragula was first checking for it. From the information you provided I don't know where you are instantiating and populating 'tasks' and 'agentTasks', but for me I managed to avoid this error by simply initialising these as empty arrays inside the component constructor (I then populate them within my component ngOnInit method).

**Comment by cormacrelf** [comment]
You can also just set the arrays to [] when you declare them:

```typescript
class Component {
  array: Array<number> = []
  // ...
}
```
It is probably slightly confusing that dragulaModel doesn't handle uninitialized arrays when `*ngFor` does. But there is nothing we can really do about that. `*ngFor` never modifies the arrays you pass it, but `ng2-dragula` has to, and if you pass a `null` or `undefined` pointer, simply changing that reference to a `[]` will not be reflected in your component, since your component's version is still pointing to `undefined`.

There is the idea of making it `[(dragulaModel)]`, i.e. two-way binding which will overwrite your arrays, but I don't see what extra utility that brings except for Immutable.js users, who are very much capable of temporarily converting to arrays at a similar cost to reconfiguring dragula.

Closing since @adunn49 is on the money.
