### ISSUE TITLE
FxFlexOrder and Ng2-dragula not Compatible

### ISSUE THREAD

**Issue by vforvasquez** [valor-software/ng2-dragula#654]
I was hoping to load some components into a column ordered by fxFlexOrder like so:
```
<div id="chairs" fxFlexOrder={{ chairsIndex }} ></div>
<div id="tables" fxFlexOrder={{ tablesIndex }} ></div>
<div id="desks" fxFlexOrder={{ desksIndex }} ></div>
```
The problem being that if fxFlexOrder is used to organize the divs ng2-dragula will not override the fxFlexOrder, or at least I have not been able to figure out how to do this.

I'm hoping to be able to store the index of each div to display them in the user's preferred order and give them the ability to change it later on via dragula. If you have any idea of how I could achieve this another way I'm all ears. I'm new to Angular2 so please don't worry if you really explain things down, I won't be offended lol.

**Comment by cormacrelf** [comment]
The point of flex ordering is to have a different order on-screen than in the DOM. This is great if you want to put some content first for search engine visibility and for blind users' screen readers to be read certain content first. But I just don't think there is a way for dragula to get an ordering other than DOM ordering, and to use any other ordering method may just complicate things too much.

In your case, I would probably just put them in a collection and sort it by the ordering field. Then, render them out in that order, and when your drop events come in, find the index of the dropped div in its parent div, and make the ordering fields in that collection match the new ordering. That means shifting the indexes along.

Fortunately, this is a common pattern. Check out the docs (i.e. README) for dragulaModel and how to sync back changes to a collection. You may wish to subscribe to the dropModel and re-compute all the ordering fields so that the ordering can be persisted.

Without testing fxFlexOrdering myself, this is the best I can do. It may be better for accessibility that you do not use flex ordering; I can't tell.

**Comment by cormacrelf** [comment]
(I'll just leave this here. It's technically possible to sort elements by their flex-order and find an element in this list to get its index: http://stackoverflow.com/a/30881362 . But it's still a bad idea. Just sort your list before you render it, so as not to need flex ordering in the first place.)
