### ISSUE TITLE
Getting wrong position on dragging-dropping into downwards direction

### ISSUE THREAD

**Issue by saumya04** [valor-software/ng2-dragula#676]
I've used a table to make the list of items sortable/draggable.
My HTML structure goes like this:
```html
<table>
  <tbody [dragula]='"drag-bag"'>
  	<tr *ngFor="let item of items | async |
    paginate: {
        id: 'server',
        itemsPerPage: per_page,
        currentPage: page,
        totalItems: total
    }; let i = index;"
    [attr.data-sequence]="item.sequence">

			<td>some content...<td>
			<td>some content...<td>
			<td>some content...<td>
			<td>some content...<td>
			<td>some content...<td>
			
     </tr>
  </tbody>
</table>
```

and the code for my angular component goes like this:

```javascript
@Component({
  templateUrl: './template_name.component.html'
})
export class TemplateComponent implements OnInit, OnDestroy {
  constructor(private dragulaService: DragulaService) {
    
    dragulaService.setOptions('drag-bag', {
      revertOnSpill: true,
      direction: 'vertical'
    });

    this._initDragulaEvents();
  }

  _initDragulaEvents() {
    this.dragulaService.drag.subscribe((value) => {
      this.onDrag(value.slice(1));
    });

    this.dragulaService.drop.subscribe((value) => {
      // Sending changed positions
      let source_obj = value[1];
      let destination_obj = value[4];
      this._interchangeSequence(source_obj, destination_obj);

      this.onDrop(value.slice(1));
    });

    this.dragulaService.over.subscribe((value) => {
      this.onOver(value.slice(1));
    });

    this.dragulaService.out.subscribe((value) => {
      this.onOut(value.slice(1));
    });

  }
}
```

As soon as I drag the first `tr` inside `tbody` towards the downwards position to the `tr` of 2nd position.

> I found that the dragula return me the 3rd element, which should be 2nd `tr`. Whereas if I move the `tr` from down to top, the dragula gives me the very correct elements in return.

Valid use-cases can be:
- If I move from 1st position to 2nd, the `dragulaService` returns me the dropped position as 3 (which is wrong)
- Whereas if I move/drag from 2nd position to 1st, the `dragulaService` return me the dropped position as 1 (which is correct)

Can you anyone tell my why its happening, is it a bug or I am implementing the plugin incorrectly :(

**Comment by cormacrelf** [comment]
What is `_interchangeSequence` doing? I can't see anything you've done wrong with dragula.

**Comment by nikolnikov** [comment]
I'm interested in a solution for this as well. I'll try and setup a Plunkr, but using the DND feature in a grid like format where all draggable cards are the same size results in the dropzone being in the wrong location. As OP said, if I have a 3x3 grid, dragging item 1 to the right has the dropzone in item 3 instead of item 2. This is pretty much the only thing preventing Dragula from being the perfect solution for me.

**Comment by paw1** [comment]
I'm facing this issue too. Will try to post a screencap

**Comment by jockejon** [comment]
Having this issue as well

**Comment by lgellert** [comment]
Running into this too.

**Comment by cormacrelf** [comment]
As far as I can tell, none of you guys are using dragulaModel. Which means none of you are using any of the code related to indexing for dragged elements. Which means not my problem. OP’s _interchangeSequence function is the location of the bug, as far as I can see, but they didn’t include the function... how do you all know you have the same problem?

Are you all trying to do your own reordering logic? You’re all going to confront the same classic reordering issue. If you remove an item at an index, everything after that shifts back. Of course you have to compensate.

**Comment by roneen31** [comment]
I have this problem too, using version `1.5.0` (Cannot update to v2 right now)
I don't have time to put together a nice plunker right now, but let me explain as simply as I can.
I use horizontal order but I think its the same.

I have a piece of code like this:
```
 this._dragulaService.drop
      .asObservable()
      .pipe(takeUntil(this.destroy$))
      .subscribe(dragulaEventArray => {
        console.log(dragulaEventArray[4]);
      });

```
And an array of elements like:

`[A] [B] [C] [D] [E]`

Now:
- If I move the element [D] upon [B], I get the element [B]
- But If I move [B] upon [D], I get the element [E]

Is this the expected behavior and I am missing something? 
And does it work this way for v2 too? (For everyone using v2)

**Comment by cormacrelf** [comment]
Well, you haven’t made clear what is different about your situation from every other working Dragula out there. All you did was describe usage that works perfectly well in the example code.

The only way to work out what’s wrong is to make a minimal example using the StackBlitz link in the Issue template (start making an issue and it will come up). You can downgrade ng2-dragula to 1.5.0 and un-migrate it. If you need it fixed, then you do have time to do that. It’s not just for the maintainers, it’s so *you* can work out what’s wrong as well.

**Comment by roneen31** [comment]
Shouldn't I get the object in which I drop upon? 
This a [stackblitz](https://stackblitz.com/edit/ng2-dragula-base-vrdmga?file=src%2Fapp%2Fapp.component.ts) reproducing what I was describing above (not sure if useful)

In my example, if I move [B] upon [D], shouldn't I get the element [D]?

Or the expected behavior is always to get the **next** element after the dropped item? And thats why you get an empty object if dropping upon the last object?

This is the first time I use dragula and I know this library is an ng2+ wrapper for the original, so if this is the expected behavior and have nothing to do with `ng2-dragula` then I apologize.

**Comment by cormacrelf** [comment]
Hm. Why do you care about event[4]? That’s ‘sibling’, which is part of Dragula ‘core’, and doesn’t even claim to represent what you “dragged on” — it’s the element you would insert a dragged element before. Of course it is different depending on whether you’re dragging to a spot before or after a particular element in the target, and sometimes it will be null (if dropped at the end of the list).

https://github.com/bevacqua/dragula/blob/master/readme.markdown#drakeon-events

As far as I can tell, you and OP are both misreading what sibling means, and we can close this as a misunderstanding. Is that right?

(Hot tip: if you’re trying to roll your own dragulaModel... the internal one doesn’t even use sibling. No need.)

**Comment by roneen31** [comment]
>**sibling is the element you would insert a dragged element before**

> you cannot  “**drag something ON something else**” in Dragula. Nothing about the visuals or mechanics suggests that you can — you can only drag an element **BETWEEN** two other elements

This! This is the piece of information that I was seeking. Now it all makes so much sense. 

> As far as I can tell, you and OP are both misreading what sibling means, and we can close this as a misunderstanding. Is that right?

You are absolutely right, we all probably misunderstood what the `sibling` is. This should be closed.

**Comment by cormacrelf** [comment]
As usual, if you actually want to drag something on something else, use my new library, https://cormacrelf.github.io/angular-skyhook/
