### ISSUE TITLE
dragulaService.drop.subscribe firing multiple times

### ISSUE THREAD

**Issue by nicolassharp** [valor-software/ng2-dragula#714]
`dragulaService.drop.subscribe((value) => {})` is sometimes firing multiple times, I can't figure out why. Does anyone have any ideas? 

Thanks

**Comment by cormacrelf** [comment]
Please add some more information. Can you give us an example? You've described some unexpected behavior and I have no way of reproducing it. For all we know, you've just subscribed to it twice. Please try to reduce your code to the simplest case which still exhibits this unexpected behavior.

**Comment by nicolassharp** [comment]
@cormacrelf thank you for responding, here's the code:

```
        dragulaService.drop.subscribe((value) => {

            console.log(value); // This happens many times... 

            this.dragging$.next(false);
            
        });

        dragulaService.drag.subscribe((value) => {
            this.dragging$.next(true);
        });

        dragulaService.cancel.subscribe((value) => {
            this.dragging$.next(false);
        });
```

I think I've work out what's happening! If I navigate away from the route, and then come back, the subscribe happens again. What's the recommended way to destroy on navigation? Thanks!

**Comment by cormacrelf** [comment]
The recommended way to destroy a subscription on navigation is never to subscribe in the first place, i.e. [just do what I posted on your other issue](https://github.com/valor-software/ng2-dragula/issues/713#issuecomment-302937608), it's *way* less complicated than unsubscribing and you'll be a better RxJS user. Also it does in three lines what is going to take you at least 10-15.

Storing observables as instance variables is great because Angular will auto-subscribe and unsubscribe from them in the `{{observable$ | async}}` bindings in your template, so you don't have to worry about it at all.

If you really must subscribe, or you have to subscribe to some other observable, you can also use a `.takeUntil` operator. This is what I recommend for all components subscribing to stuff: when `this.destroy$` fires, the observable produced by `.takeUntil(this.destroy$)` will 'hang up' and the subscribers will die. The good thing is you don't have to manually store subscription objects in an array and terminate each of them in sequence in your `ngOnDestroy`.

```typescript
// somewhere (probably only once in your whole project, rxjs/add/... is global
import 'rxjs/add/operator/takeUntil';

export class MyComponent {
  private destroy$ = new Subject();

  constructor (private dragulaService: DragulaService) {
    dragulaService.drag.takeUntil(this.destroy$).subscribe(() => {
      // ...
    )
  }

  ngOnDestroy() {
    this.destroy$.next();
  }
}
```

**Comment by nicolassharp** [comment]
@cormacrelf Awesome! Exactly what I was looking for, it works and I learnt something. Thank you!

**Comment by raulrene** [comment]
@cormacrelf or to anyone else coming upon this issue, there's a better alternative than listening for onDestroy. Specify `viewProviders: [DragulaService]` in your `@Component` declaration. See here https://github.com/valor-software/ng2-dragula/issues/828

**Comment by cormacrelf** [comment]
@raulrene Mate. **Do not add it as a viewProvider.** It just means more people come running to the issues page with wasteful support questions about hard-to-reproduce problems dragging between different components, which is meant to be core functionality.

If it were not valuable to drag between components, then the library would not have been structured as a singleton service. Given that it is, and that all the code here expects one singleton service object, please use it as one.

If you get sick of unsubscribing, just use the RxJS Subscription#add method to chain together all your component’s subscriptions into one Subscription object. Or use `@ngrx/utils` and its fancy decorator. (Yes, the solution I posted above is too complicated for its purpose.) But please don’t break this library on purpose and then recommend it to others!

**Comment by roneen31** [comment]
Adding `this._dragulaService.drop.unsubscribe();` in `ngOnDestroy` fixed it for me.

After searching it a bit I realized that my problem was that in `ngOnDestroy` I was only destroying the dragulaService with : `this._dragulaService.destroy('my-bag');` 
But I was not unsubscribing.
So if the component was recreated the drop event was running 2 times.

**Comment by cormacrelf** [comment]
That advice is not relevant to version 2+. DragulaService.drop is a function now. I don’t think you could call unsubscribe on it in v1, for that matter.

**Comment by roneen31** [comment]
Forgot to mention this is for `1.5.0` version, as the question is also old.

After trying again, the unsubscribe does not work as I thought (not sure why I thought it worked in the first place). Ended up using the solution you provided above, thanks.
