### ISSUE TITLE
Ang2 -- ng2-dragula -- Multiple constructor implementation not allowed

### ISSUE THREAD

**Issue by SGissubel** [valor-software/ng2-dragula#761]
Hello everyone!  

I am trying to get dragula working for an app I am working on.  I am trying to allow a user to drag and sort items in a list.  Dragula seems to be a good option (also, already been used in the app elsewhere).  But I am running into one major issue:

Every source mentions that you need to add a constructor to the component file, but I already have a constructor(private... in the component file (doing something completely different - unrelated to dragula ).  Any thoughts on any way around this?  Or how to implement two separate constructors?  

firstone: 
(necessary -- not my code, but needs to be run here)

`  constructor(private apiService: ApiService) {
    let that = this;
    apiService.get(apiService.urls.faq).subscribe(
      data => that.handleFaqResponse(data),
      err => that.handleFaqResponse('err'));
    }
`
second one -- dragula -- the code I need to work 

   `   constructor(private dragulaService: DragulaService) {
    dragulaService.drag.subscribe((value:any) => {
      console.log(`drag: ${value[0]}`);
      this.onDrag(value.slice(1));
    });
.................
`

**Comment by cormacrelf** [comment]
You're new! Just add DragulaService to the arguments to the existing constructor.

In JS/Typescript, there is only one constructor, and it's the function that gets called when you run `new MyComponent(...)`. In fact, once you have created a class (e.g. `class MyClass { }`), MyClass _is_ a constructor function. 

Angular might be confusing because you never explicitly call that, the injector does.

**Comment by SGissubel** [comment]
Thanks! Yep...I figured it out a few days ago.  Thank 

constructor(private apiService: ApiService, private dragulaService: DragulaService) {...
...
}
