### ISSUE TITLE
Bug with loss of focus input inside container directive

### ISSUE THREAD

**Issue by Ts-alan** [valor-software/ng2-dragula#773]
If we place the input inside dragula directive -we have bug with loss of focus from input when we click on container of dragula directive.
![image](https://user-images.githubusercontent.com/9947228/30648949-ecc5a01c-9e27-11e7-9778-07c6df8f0dfa.png)

It seems a problem in this part of the code
![image](https://user-images.githubusercontent.com/9947228/30648971-fd136404-9e27-11e7-9503-55118d7ea84a.png)

Is it possible to fix this  something?

**Comment by benelliott** [comment]
This is likely to be an issue with [dragula itself](https://github.com/bevacqua/dragula) rather than the Angular wrapper but I recently had a similar issue and fixed it by reworking that logic a bit. You can see my fork [here](https://github.com/benelliott/dragula). Can you provide a plunkr or similar to show your issue?

**Comment by Ts-alan** [comment]
https://plnkr.co/edit/aY5CXoh7nCrGE3YIWAb7?p=preview
If I click on input then the focus is not removed from an input when clicking on a green square(hence the event blue does not work)
 Are @benelliott have you npm package for our repository?

**Comment by benelliott** [comment]
I won't publish it on npm as it is just a fork, but you can point npm at a GitHub repo with the syntax `"dragula": "github:benelliott/dragula#8002d72"`.

I can't really understand what you're trying to achieve from your plunkr though - do you mean that you wanted the input to lose focus when you drag the green container? Could you add some logic to the controller?

**Comment by Ts-alan** [comment]
No.The green container contains dragula directive( in other words, dragula directive is applied to green container) 
If I do first click on the input
![image](https://user-images.githubusercontent.com/9947228/30960990-6706aab2-a44d-11e7-9571-8a305d51e635.png)
then if i do click on green container- focus on input remained
![image](https://user-images.githubusercontent.com/9947228/30961202-1e57cff2-a44e-11e7-896c-725524473755.png)
If i not do click on  on green container,click on elsewhere -focus on input disappear
![image](https://user-images.githubusercontent.com/9947228/30961362-973120b8-a44e-11e7-8144-7ef5377aea50.png)
I will need that focus  will disappear when i click on green container

**Comment by benelliott** [comment]
Oh I see! I think that this issue is due to the fundamental way that Dragula works and I don't think it's a bug with this wrapper. I would suggest implementing a workaround by hooking onto the container's mousedown event and using it to blur the input like so: https://plnkr.co/edit/pEKcTb7cfKZ6f0tYGVaH?p=preview
