### ISSUE TITLE
Memory leak for dynamic dragula data - how to prevent? 

### ISSUE THREAD

**Issue by Hitchki** [valor-software/ng2-dragula#794]
I am implementing a calendar component for the distribution of resources with the resources as the x-axis and the days of (a given) week as the y-axis. 
Users can select any week of the year – which means that the data for the calendar changes quite often. 

The Input for the calendarComponent (named resourcesDaysArray) comes from another component as follows:
<calendar DaysArray]="(resourcesDaysArray$ | async)" ></calendar> 

The calendar just takes the input:
@Input() resourcesDaysArray

And then shows it in the html:
<div *ngFor='let resource of resourcesDaysArray'>
  <div *ngFor='let day of resource' class='container' [dragula]='"bag-one"'>
    <div *ngFor='let calendarItem of day?.calendarItemsDataArray'>
      // show calendarItems with there data here
    </div>
  </div>
</div>
 
resourcesDaysArray is a quite huge multidimenisonal arry in the form: 
  resourcesDaysArray1: Array<any> = [
    [   // resource1 
      ['calendarItem11', 'calendarItem12'],  // monday
      ['calendarItem21', 'calendarItem22'],  // tuesday
      ['calendarItem31', 'calendarItem32'],  // wednesday
      ['calendarItem41', 'calendarItem42'],  // thurssday
      ['calendarItem51', 'calendarItem52'],  // thurssday
    ],
    [ // resource2
      ['calendarItem1', 'calendarItem2' ]
        ....
    ]
  ];

And as said before the resourcesDaysArray is not fixed but changes (as an input from another component).
Whenever I am changing the week (and therefore the input ), my browser takes some memory - without freeing it up later on. 

When I remove the dragula bag, the amount of memory taken by the browser is stable.
With other words, I have a considerable memory leak. Somehow dragula seems to prevent that the old data can be garbage collected by the browser. 
 
So my question is: Am I doing something wrong? Or is it even a known problem? 
Any help would be appreciated.

**Comment by cormacrelf** [comment]
Please force a GC cycle using the dev tools and report back.

**Comment by levatisFontAwesome** [comment]
Please see attached my logs made with the chrome dev tools / memory.

My test procedure was to always change from week 45 to 44 and back.

In between I pressed the garbage collector symbol.
After each change of week (e.g. from week 45 to week 44 I took a heap snapshot.

This is giving the following result:
1-WK-45-Heap-20171110T151629.zip	(heap at the begining - week 45)
2-WK-44-Heap-20171110T151732.zip	(heap after changing from week 45 to 44)
3-WK-45-Heap-20171110T151928.zip	(heap after changing from week 44 to 45)
4-WK-44-Heap-20171110T152004.zip	(heap after changing from week 45 to 44)

From the heap snapshots one can see very easily that the amount of e.g. HTMLDivElements is growing with every change of the week data.

This only happens when I use dragula bags in the calender items. After removing the dragula bags in the calendar items, the amount of 

And also after remove dragula the growth of the memory heap is gone and the amount of HTMLDiv elements is stable ().

So this last point brings me to the conclusion that must have something to do with dragula.

If you need some more data from my side please don't hesitate to tell me.
We absolutelly like dragula and therefore we would be very glad to solve this problem.

PS.: I also experimented with destroying the dragula bag before changing the week (as mentioned in issue 442) - but so far with no result.

https://github.com/valor-software/ng2-dragula/issues/442


[1-WK-45-Heap-20171110T151629.zip](https://github.com/valor-software/ng2-dragula/files/1461851/1-WK-45-Heap-20171110T151629.zip)
[2-WK-44-Heap-20171110T151732.zip](https://github.com/valor-software/ng2-dragula/files/1461854/2-WK-44-Heap-20171110T151732.zip)
[3-WK-45-Heap-20171110T151928.zip](https://github.com/valor-software/ng2-dragula/files/1461855/3-WK-45-Heap-20171110T151928.zip)
[4-WK-44-Heap-20171110T152004.zip](https://github.com/valor-software/ng2-dragula/files/1461856/4-WK-44-Heap-20171110T152004.zip)
[WK-45-44-45-44-Heap-20171110T152313.zip](https://github.com/valor-software/ng2-dragula/files/1461857/WK-45-44-45-44-Heap-20171110T152313.zip)
[WK-45-44-five-times-Heap-20171110T153354.zip](https://github.com/valor-software/ng2-dragula/files/1461858/WK-45-44-five-times-Heap-20171110T153354.zip)

**Comment by snorbi07** [comment]
For anyone bumping into this issue, the solution is to have an _ngOnDestroy_ with the following snippet:

```
ngOnDestroy() {
	const bag = this.dragulaService.find(this.dragula);
	const itemToRemove = bag.drake.containers.indexOf(this.el.nativeElement);
 	if (itemToRemove !== -1) {
		bag.drake.containers.splice(itemToRemove, 1);
	}
}
```
According to dragula's documentation you can add/remove items from containers, currently the wrapper never removes them and thus we end up with leaks.
A quick and dirty solution is to use your own wrapper that extends the current directive, a proper one would be a PR. I'll try to get around to that as well...

**Comment by Hitchki** [comment]
I was wondering if you succeede in solving the problem of the data leak and if so how you did it.
Can you enhance a bit on how to make such a wrapper?
What do you mean with PR?

**Comment by Hitchki** [comment]
@snorbi07 
I was wondering if you succeeded in solving the problem of the data leak and if so how you did it.
Can you enhance a bit on how to make such a wrapper?
What do you mean with PR?
Any information is highly appreciated!

You said: "currently the wrapper never removes them and thus we end up with leaks!"
Does that mean that your data snippet for the ngOnDestroy() does not work without making such a wrapper?

**Comment by Hitchki** [comment]
Closed it unintentionally...

**Comment by snorbi07** [comment]
Currently the Angular based [dragula wrapper](https://github.com/valor-software/ng2-dragula/blob/master/src/components/dragula.directive.ts) does not take care of the deallocation of objects. 
A proper fix would be to add the _ngOnDestroy_ lifecycle hook to it and this is what I meant by creating a pull request that sorts that out.

Since we were very short on time, I forked ng2-dragula, added the _ngOnDestroy_ implementation I shared in my previous comment and used that version. The other solution is that you create your own directive by extending _DragulaDirective_ and add the _ngOnDestroy_ to it. Afterwards you replace all _dragula_ directives with your own.

Hope this helps!

**Comment by alexandermikuta** [comment]
@snorbi07 Could you do a pull-request of your solution instead of a fork. I think this would be helpful for many dragula users.

**Comment by snorbi07** [comment]
@alexandermikuta Sure, I'll do it.

**Comment by alexandermikuta** [comment]
@snorbi07 Any news about your pull-request?
