### ISSUE TITLE
Updating dragulaModel data- not reflected in list

### ISSUE THREAD

**Issue by Inigo-Pascall** [valor-software/ng2-dragula#804]
I have the following `ul` list implementing dragula:

`<ul [dragula]="parent + '-bag'" [dragulaOptions]="getDragOps(parent)" [dragulaModel]="_treeService.tree">`

This is working well, and changes made through re-ordering the list are reflected back to the `_treeService.tree` array. However, if I add an element to this array from another component, it doesn't appear in the list (even though it has definitely been added to the array).

I guess I'm missing something here, but I thought `[dragulaOptions]` was supposed to sync changes automatically, including new items? What do I need to do to get it to show the updated array?

Thanks

**Comment by inv-senchuthomas** [comment]
@InigoWD  
 Have you got the solution for this issue. I am also struggling with the same issue for a week. If you are found any solution please mention

**Comment by InigoWD** [comment]
Hi @inv-senchuthomas. I'm afraid my "solution" was simply to destroy and dynamically recreate the bag each time a node was added. For my specific situation this is acceptable, though I appreciate it's hardly ideal. Here's a snippet from my code if it helps...

```
  initialize(bag_id){

    this.killDragula();

    this.select_mode = 'dragulaActive';
    this.manipulate_nodes = true;
    this.addNodeInputActive = false;

    this.activeBag = bag_id;

    this.dragulaService.setOptions('gridBag', {
          axis: 'y',
          mirrorContainer: document.getElementById('cat-tree-builder'),
          moves: function (el, container, handle) {
            return handle.classList.contains('handle-' + bag_id);
          }
        }
    );

    this.dragulaService.find('gridBag').drake.containers.push(document.getElementById(bag_id + '-bag'));
    this.dragulaService.find('gridBag').drake.models = [this.dragBags[bag_id + '-bag']];
  }
```

**Comment by ipuszkie** [comment]
+1, having the same problem using a tabbed component. Each time i change tabs (both with draggable content), the bag loses the options.

**Comment by cormacrelf** [comment]
You appear to be confronting Angular change detection. I'm guessing `_treeService.tree` is an array property on a service.

Just because two components have a reference to and manipulate the same array, doesn't mean that the changes are automatically propagated through Angular change detection. Your service does not have the ability to trigger change detection on components it doesn't know exist, when an array on it is modified internally. 

The problem with using dragulaModel is that it just manipulates arrays, it cannot call `.next` on a Subject. You simply cannot share a mutable array reference and expect Angular to figure out which components need updating across your entire app. For that reason, I do not recommend dragulaModel. Just subscribe to the events and call `.next` on a Subject on your service in there.

**Comment by oliwin** [comment]
I have the same problem

**Comment by trobbertze** [comment]
I think I am having the same issue as this.

I am using ngFor with an array.  When I push something into that array it works as expected, but when I splice the array the item does not get removed from the DOM.

This is my template:
`
<div id="desktop" class="desktop" dragula="desktop">
    <deal-tile
        *ngFor="let tile of displayTiles"
        (reportError)='displayError($event)'
        (onSetCurrencyPair)='setCurrencyPair($event)'
        [id]="tile.id"
        [currencyPair]="tile.currencyPair"
        (close)="onClose($event)"
    ></deal-tile>
</div>
`

`
onClose(tileId: string) {
    const index = this.displayTiles.findIndex(o => o.id === tileId)
    this.displayTiles.splice(index, 1)
    window.localStorage.setItem('tiles', JSON.stringify(this.displayTiles))
}
`

When I remove the `dragula="desktop"` from the template it works as expected.

So I guess my question is the following.  Is there a way to force the update?  Or is there a way to remove models from code?  I went through the source and it doesn't seem so.
