### ISSUE TITLE
nested drag and drop breaks angular animation

### ISSUE THREAD

**Issue by romain10009** [valor-software/ng2-dragula#826]
My code is two drag and drops nested With different animations it wont work.

Issue : If you drag and drop a top level element that is closed, and then click on it to open it, it won't animate the list of nested elements in.

[https://plnkr.co/edit/3pyHZVrJeeGCa4aQiL6o?p=preview](url)

I tried under various angular version (4.4.6, 5.1.2 and 6.0.0-beta.2), issue persists.

**Comment by cormacrelf** [comment]
Got plunk working again... line 124 now checks `Event.target` instead of `Event.srcElement` (not a real API)

https://next.plnkr.co/edit/wFvwwGwXkABAG76F

I don't see anything wrong with the 'bug on' case. It is actually the correct animation code for your situation.

See, you have an `*ngIf="showBug && folder.show === 'open'"` so the entire files list gets added and removed from the view entirely. Therefore 'void' is the correct animation state to represent disappearing.
