### ISSUE TITLE
prevent an item to be dropped at particular position

### ISSUE THREAD

**Issue by Survey2Connect** [valor-software/ng2-dragula#827]
I have an array of items on which dragula is applied.  I want a particular item not to be a part of dragula.
I have tried accepts and move. They work well for the item not to be dragged but I even want its position not to be changed when some other item is dragged and dropped below it. I want that item to be stick at its original position and rest of the items to be dragged and dropped. How would I be able to achieve this ?

**Comment by jaumereg** [comment]
I need that too, if someone can help us it will be really useful :)

**Comment by LargatSeif** [comment]
i need that too

**Comment by kajdzo** [comment]
I'm having the same issue, any news on this?

**Comment by cormacrelf** [comment]
I don’t get it. What happens when you drag A below Fixed?

    A
    Fixed
    B

**Comment by cormacrelf** [comment]
Do you mean you want a header? Like the first item never changes.

Just wrap the draggable items in another div and leave he header out. Not that hard.

**Comment by cormacrelf** [comment]
Closing because you couldn’t do it even if somebody could give me a real non-header use case. It’s just not something you gave any power over, except for the moves function.

**Comment by harleenarora** [comment]
I need that too, if someone can help us it will be really useful in my project.

**Comment by MNorgren** [comment]
Also need this. Example would be nice.

**Comment by cormacrelf** [comment]
@MNorgren again, I don’t know what you guys all apparently agree the problem means. Every now and then someone pipes up wanting an example. But answer me this:

How is problem not solved by putting non-draggable items outside the div with Dragula on it? You can do two Dragula divs with other thing in between as well. And the move should function. What are you all wanting that isn’t covered by these suggestions?

**Comment by MNorgren** [comment]
@cormacrelf - You seem to be getting quite defensive and upset at everyone who requests this feature. The feature being requested is supported by the Angular CDK and a demo of the request can be found here:
https://v7.material.angular.io/cdk/drag-drop/overview

The second to last demo will let you drag even numbers from one container to another, but not odd numbers. It may be good to add this to your demo as well if this functionality is supported. 

As of now, I am switching over to Angular CDK and will recommend anyone else having this issue to do that as well.

**Comment by cormacrelf** [comment]
I’m not angry, just waiting for someone to make a comment I can actually help them with. In your case, you would use a dead simple combo of the moves and accepts parts of the main Dragula API with some data attributes on the elements. It is still quite different from the original comment though.

However, I completely support moving away from ng2-dragula. Upstream is unmaintained. Cdk is good. A lot of folks here are toiling away at old codebases, and when they ask for help I do have to make sure they’re not just waving at the lifeguard before diving in. Best of luck.

**Comment by webmasterlv** [comment]
I just had exactly the case where I need this. The reason is, sometimes user should not be able to change positions of some of the items, as in my case, user uploads photos, but due to particular circumstances, he is forbidden to change first image position (like, the first image is gallery thumbnail and user is forbidden to change it).

As for the logic how it works. If, while dragging, it is detected that there is locked image between old and new position, the new element is not lifted alongside the sibling, but they swap places. If there is no locked element between them, sort as usual.

For example (* - locked element):

`A
B
C*
D`

If i drag A after C, it becomes

`D
B
C*
A`

It is more easy when locked elements are at the start or end of the list:

`A* B* C D`

In this case, only C and D can be moved (this actualy is pretty easily solvable in `accepts` function).

So the locked element is always in exact index, no matter how you sort the others. I partially solved it with `accepts` function (luckily it gives me `sibling` argument so I know where new element will be dropped and I return false when trying to drop on locked element), but i still struggle with another use cases.

**Comment by cormacrelf** [comment]
@webmasterlv

Again:

> How is problem not solved by putting non-draggable items outside the div with Dragula on it?

Just write the code by splitting the array grouping by locked status, and producing as many Dragula and non-Dragula divs as are necessary to create this behaviour. Translate indices back into the original positions and implement the move logic yourself. I’m just flat-out not going to do it for you, so give it a go and share your solution here if you make progress.

**Comment by webmasterlv** [comment]
@cormacrelf 
Yeah I'm just sharing what issues I have come up with, surely there's no requirement to do something. The problem with splitting into containers is CSS. If elements are stacked vertically, then no problem, however, if you have container where items should be laid out horizontally, it's very hard to make a correct grid of items.

**Comment by webbby** [comment]
> @cormacrelf
> Yeah I'm just sharing what issues I have come up with, surely there's no requirement to do something. The problem with splitting into containers is CSS. If elements are stacked vertically, then no problem, however, if you have container where items should be laid out horizontally, it's very hard to make a correct grid of items.

Absolutely there are cases where the layout is complex enough to separate containers. 
And there are cases where things might be dynamic so you can't handle it with fixed containers separation.
And the `move` function works with siblings when moving in the same container but not when you move item from another so it is not .
That is and obvious flaw  and it is really bad when users meet such stubbornness of against their request of feature that is also a poor design issue.

**Comment by Stefan-Kosker** [comment]
I have a solution to this. But first: Since mr Cormacrelf was telling, that there is no real use case and denying to implement this feature, here is a legit use case:

![image](https://user-images.githubusercontent.com/13136881/92336321-96e0c280-f09f-11ea-976e-a767f088397f.png)
The "Bild Einfügen" Element must always stay in first place. Besides of that, there is no clever possibility of creating a 2-3-3- ... layer without weird flexbox magic. Believe me, I tried and it worked. But the code was a real pain in the ass.

Anyways, enough talking about possible use case. Here is the solution, if the element must always stay on top **(which I believe is the requested feature all along)**

First of all, add a HTML Class to the non-draggable element:

```
    <div class="do-not-drag">
```

Then, when you are creating your dragulaGroup, add following configuration to Options:
```
    const dragulaOptions = {
      invalid: (el, handle) => el.classList.contains('do-not-drag'),
      accepts: (el, target, source, sibling) => !sibling.classList.contains('do-not-drag')
    };
```

I hope this helps some fellow dev. Please add this to the docs. I know, the readme tells about invalid and accepts, but apperantly it is not clear enough about fixating an element to a position

Have a nice day

**Comment by Stefan-Kosker** [comment]
Update: My Solution from 8 days ago is not working because dragulaModel just dont work with unmovable elements. As @cormacrelf told here in another issue: https://github.com/valor-software/ng2-dragula/issues/506#issuecomment-305743009

yeah sad tho... A very promising repository here. But yeah... Sucks to be having a design decision
