### ISSUE TITLE
Drag and drop in closed material accordion

### ISSUE THREAD

**Issue by costea93** [valor-software/ng2-dragula#837]
Guys, i use ng2-dragula and have this blocker:

https://stackoverflow.com/questions/49053863/drag-and-drop-in-closed-material-accordion

It's possible somehow to do that?

**Comment by cormacrelf** [comment]
Not really possible, at least not obvious.

The problem is that there is no such thing as a plain drop zone in Dragula. It is Trello-style or bust. You could have an empty div with a min-height, that only displays when your accordion is closed, and make it part of the bag. Then, explicitly handle drop events by:

1. Making sure you re-render with a very empty div
2. Adding the item to the list proper.

It might work to attach Dragula to the whole element, but it makes for a messy template to have a top-level conditional. That’s the best I can think of. It’s not very clean, but that’s what my other drag and drop library is for.
