### ISSUE TITLE
accepts options not working in case of multiple item drag and drop functionality

### ISSUE THREAD

**Issue by dhiraj3301** [valor-software/ng2-dragula#869]
Hi,

I tried to implement the multiple item drag and drop functionality by following way,
When user selected the tiles from source i am adding 'selected' class to particular div

then in this.dragulaService.drag.subscribe i added the code to get all divs with selected class and then added it in e.innerHtml so then its showing multiple items dragging and dropping and its working fine

But on the top of this i wanted to implement the functionality that in the source container i don't want to allow user to drag-drop in same container (i.e. I don't want user to allow to change sequence in only source container but allow in destination container), I tries by setting the accepts option but it not working when i am doing multiple select (It works fine when i do drag drop one item only), Is there any other way how i can restrict user to not drag drop in same container only for source container in case of multiple item drag and drop?

Or is there any other better way to implement multiple item drag and drop,

Thanks,
Dhiraj

**Comment by cormacrelf** [comment]
Multiple drag and drop is your code. I can’t help you with that because I can’t see it, and moreover, nobody in open source has that much free time.

As far as your problem goes, I think you can do at least a cursory search of the existing issues and read the demo code. I am about 90% sure this has been done to death.
