### ISSUE TITLE
dragula ngFor update incorrectly

### ISSUE THREAD

**Issue by dglsn** [valor-software/ng2-dragula#872]
I use a ngFor, if two items have the same value, these two disappear from bucket when i drag on of these. The other one stay in my array but isn't displayed in view

**Comment by dglsn** [comment]
I don't have a trackBy function. But I don't see how i can use it with array

**Comment by cormacrelf** [comment]
I think ng2-dragula does `yourArray.findIndex(dragged)` or something to that effect, and picks up the first one it finds.

Don’t use plain numbers or strings, because `1 === 1`. You can’t use the same object in two spots in the same list, clearly. It’s not difficult, just use `{ value: "..." }` to wrap simple values or just abstain from having two references to the same object.

Ultimately, I can’t think of any situation I would want or end up with the same object twice in the same list. I could maybe consider it a bug if you post a stackblitz or plunk showing a reproduction and it turn out really incongruous, but I just doubt it.
