### ISSUE TITLE
[usage question] how to ignore header element in table

### ISSUE THREAD

**Issue by zualexander** [valor-software/ng2-dragula#884]
- [x] My issue title starts with `[usage question]`
- [x] I have thoroughly read through the README, and I have looked at the demos to see if my use case has obvious examples.
- [x] I have read the [dragula docs](https://github.com/bevacqua/dragula).
- [x] I have searched through the **[`ng2-dragula` issues](https://github.com/valor-software/ng2-dragula)** for related problems, including closed issues, and I didn't find anything.
- [x] I have browsed through [the issues labeled "future reference"](https://github.com/valor-software/ng2-dragula/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22future+reference%22).

### Use Case
I'm using the angular/material data-table and want to use dragula to change the order of the table-itmes.

### Usage

https://stackblitz.com/edit/angular-cg8ysm?file=src%2Fapp%2Fapp.component.html

### Problem
I added two tables which should show the problem. In the second one, the header row is missing - there it does work like expected, but I would need the header like in the first table above. 

The reason I know (because I read in the other issues), is that there is an element (the header in this case) - which does not belong to the model. with the angular material data-table, there is no option to use the dragulaModel otherwise.

* is there an option to add the dragulaModel in the createGroup somehow? -> Then I wouldn't need anything in the template and would make a group just for the TBODY with the `isContainer` option.
* Is there another some could do this?
* If there is nothing implemented yet, where/how would you do it? I would then create a PR for this option if there is a need for it. (-> my first idea was to add a `modelSelector` to the options object, and in the `domIndexOf` check if it is set, and just return the index of the elements which match the selector.

Best Regards Alex

**Comment by cormacrelf** [comment]
Even if you did add a selector function, you would still have the problem that Dragula lets you pick up the header element. And drop it below the rest. And drop items above it. I can’t make Dragula not do this. I don’t think this is acceptable to anyone who wants headers, even if they only don’t mind because they haven’t accidentally triggered it in that weird state of mind known as “it worked on localhost”.

That is why there is a dedicated section in he README.

You can build a basic sortable pretty quickly in https://cormacrelf.github.io/angular-skyhook/ that doesn’t have this problem. In the example code, each element keeps track of its own index and making itself draggable. It would work as a directive you attach to those weird mat components using a host ElementRef and the programmatic API on DragSource and DropTarget. When I get some time I will publish the super powerful abstraction over the sortable pattern used in the Trello example, but it’s not ready yet as a 1.0 API.

**Comment by cormacrelf** [comment]
It is of course possible to use isContainer, but you won’t be able to use it with dragulaModel at all.

**Comment by zualexander** [comment]
@cormacrelf thanks for your kind answer, will try it with skyhook!
