### ISSUE TITLE
[usage question]How Drag and Copy Angular Components

### ISSUE THREAD

**Issue by strangegt** [valor-software/ng2-dragula#905]
**REQUIRED: Before filing a usage question**

Change each `[ ]` to `[x]`  when you have done it.

- [x] My issue title starts with `[usage question]`
- [x] I have read the [README](https://github.com/valor-software/ng2-dragula), especially the ['classic blunders' section](https://github.com/valor-software/ng2-dragula#classic-blunders)
- [x] I have looked at the [demos](https://valor-software.com/ng2-dragula/) to see if my use case has obvious examples.
- [x] I have searched the [`ng2-dragula` issues](https://github.com/valor-software/ng2-dragula/issues), including closed issues.
- [x] I have browsed [the issues labeled "future reference"](https://github.com/valor-software/ng2-dragula/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22future+reference%22) for problems that have been solved before.

**Use case description (required)**
I want to copy a component form one place to another, but no new component is created.

A clear and concise description of what you want to achieve.
I got a component, here a sample for testing
```
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-my-component',
  templateUrl: './my-component.component.html',
  styleUrls: ['./my-component.component.css']
})
export class MyComponentComponent implements OnInit {

  @Input() title = 'Titulo';
    constructor() {
    console.log('MyComponentComponent created');
   }

  ngOnInit() {
    console.log('MyComponentComponent ngOnInit');
  }
  onSave() {
    const fecha = new Date();
    this.title = fecha.toLocaleDateString() + ' ' + fecha.toLocaleTimeString();
  }
}
```
with this html
`<div style="border:1px solid black;">{{title}} <button (click)="onSave()">Update</button></div> `

This is the source for drag, another component with this html inside , then component code dont matter
```
    <div dragula="MYCOMPONENT" id="editor-tools">
      <div><app-my-component title="Titulo 1"></app-my-component></div> 
      <div><app-my-component title="Titulo 2"></app-my-component></div> 
      <div><app-my-component title="Titulo 3"></app-my-component></div> 
      <div><app-my-component title="Titulo 4"></app-my-component></div> 
      <div><app-my-component title="Titulo 5"></app-my-component></div> 
      <div><app-my-component title="Titulo 6"></app-my-component></div> 
    </div>

```
The target is:
```
<div dragula="MYCOMPONENT" style="min-height:50px;">
</div>
```
The service is configured in a parent component.
```
constructor(private dragulaService: DragulaService) {
    dragulaService.createGroup('MYCOMPONENT', {
      copy: (el, source) => {
        console.log(el, source);
        return  source.id === 'editor-tools';
      },
      copyItem: (person: EmailRowComponent) => {
        return new EmailRowComponent();
      },
      accepts: (el, target, source, sibling) => {
        // To avoid dragging from right to left container
        // console.log(el, source);
        return target.id !== 'editor-tools';
      }
    });
   }
```
I work i can drag and drop, the a new item is added to destination, also reorder in destination, but no new component is created, the button dont work, if look the element inspector in chrome the tag <app-my-component> is created but no new component

How can create new component on drop

**Can you show a demo, or a picture of what you want to achieve?**

If so, please link it here.

**Additional context**

Add any other context here.

**Comment by cormacrelf** [comment]
You're not rendering a new component in the target. There will never be a new component in there, because the template is just an empty div, and Angular will just ignore it.

Use `[dragulaModel]`. Read the docs.

**Comment by andrewryan1906** [comment]
I've read the docs - over and over, and I cannot figure out how to do this.

I've got a toolbox of Angular components for a form creation wizard. Each angular component has behavior... when I drag it from my toolbox onto my canvas, I need to interact with it on the canvas. So I need Dragula to make a copy not just of the DIV, but of the whole Angular component.

Cannot figure out how to do this... any help would be greatly appreciated.

**Comment by cormacrelf** [comment]
@andrewryan1906 The default case of this library is indeed just to copy divs. DragulaModel is a hack to cause the parent component to re-render, possibly with an additional item in a list (and hence another component in your case). It’s not that conceptually difficult, there is nothing transformatively different about using components instead of divs. Nowhere in the process is a “copy... of the whole Angular component” required. People seem to get stuck on that a lot; you literally can’t copy an instance of a component AFAIK, and you never need to. Just put the same data in a template somewhere else and you’re good. When you do it with Dragula, technically it will clone DOM and the new component will either attach itself to that DOM or delete it and render a new one (I can’t remember). But I can imagine struggling if you are using OnPush, for example, because suddenly one part of that puzzle disappears and the parent may never re-render.

It is not a good library for you in general. Try https://cormacrelf.github.io/angular-skyhook/ instead. There, the logic and state are completely separated from the DOM.

**Comment by andrewryan1906** [comment]
Thanks for your reply. And I really appreciate you pointing me to the more
powerful library.

I think I may have a workable solution that doesn't require me to learn
another library. I use *ngFor to create two copies of my component, and I
show the first one but hide the second. So if I have:

COMPONENT 1
COMPONENT 1 (hidden)
COMPONENT 2
COMPONENT 2 (hidden)

I bind the *ngFor to an array. When I drag Component 1 off of the board, I
flip the visibility switch on the second copy of COMPONENT 1 (making it
show up on the palette), and then I add another entry to the array for
COMPONENT 1 right before COMPONENT 2, effectively copying it. To the user,
this looks like entire copies of the component are being made.

The reason why I have to always have two component 1's, instead of just
creating a replacement copy of component 1 upon move, is that if I try to
add a new component 1 after the move it appears in the destination DIV, not
the source DIV, and I couldn't figure out why. So instead I create the new
copy after Component 1 (hidden), but before Component 2 - and it works.

I'll see if this works, and if not, I'll look at the skyhook.

Thanks!
Andrew

**Comment by cormacrelf** [comment]
A few things
- subsequently added components not an ngFor are inserted as siblings of existing ones. Because your new ones are showing up on the canvas, that tells you that you’re not copying DOM at all, you’re literally moving their entire Dom tree, and ngFor has no idea. And those components still live under the side panel. I will reiterate that it isn’t possible to copy components so you are not doing that.
- that also means, and I hate to say this, but: you’re probably writing yourself down a bad path. You should move things onto the canvas programmatically by appending to an array or whatever. Dragula is secondary, and it’s mainly good for inserting into arrays and hoping you re-render over the damage it has done to the DOM in the process. You’re using the DOM a source of truth. That’s backwards.

Why not use `copy: true` and `copyItem` as described in the docs? And handle dropModel events on the canvas?
