### ISSUE TITLE
Unable to reuse DraggableDirective of dragula for two different components

### ISSUE THREAD

**Issue by chaitalik22** [valor-software/ng2-dragula#955]
I have two components each of them injecting the same draggable service and using the same directive in HTML.

I am not able to use single directive for two components.
It is showing me following error.

TypeError: Converting circular structure to JSON when using dragula 

Please help me with this as soon as possible

**Comment by cormacrelf** [comment]
The code that used JSON.parse(JSON.stringify(x)) to copy items was removed ages ago. Your own code may be including a JSON round trip, so investigate that. Please use the issue template to report actual bugs when you are suspicious they are due to ng2-dragula; if this were a library problem, the details you provided are not much to go on.

https://github.com/valor-software/ng2-dragula/commit/78f3f9f1917dc765ff9cca6ee5eb25d4775be3de
